---
driver:
  name: terraform
  root_module_directory: test/fixtures
  parallelism: 4

provisioner:
  name: terraform

platforms:
  - name: azure

suites:
  - name: single_subscription
    driver:
      root_module_directory: test/fixtures/single_subscription
  - name: single_subscription_k8s
    driver:
      root_module_directory: test/fixtures/single_subscription_k8s
