---
driver:
  name: terraform
  verify_version: false
  root_module_directory: test/fixtures
  parallelism: 4

provisioner:
  name: terraform

platforms:
  - name: azure

suites:
  - name: single-subscription
    driver:
      root_module_directory: test/fixtures/single-subscription
  - name: single-subscription-k8s
    driver:
      root_module_directory: test/fixtures/single-subscription-k8s
