name: CI - Integration Tests

on:
  pull_request:
    paths:
      - '**.tf'
  push:
    branches:
      - master
    paths:
      - '**.tf'
concurrency: terraform
jobs:
  integration_test:
    name: Test-Kitchen
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      TF_VAR_sysdig_secure_api_token: ${{secrets.KUBELAB_SECURE_API_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Login to Azure
     	uses: azure/login@v1
       	creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run test
        run: bundle exec kitchen test

      - name: Destroy resources
        if: ${{ failure() }}
        run: bundle exec kitchen destroy
