name: Secret Test

on:
  pull_request:
  push:

jobs:
  show_secret:
    name: azure sub
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_ARM_TENANT_ID}}

    steps:
      - name: Run Workflow
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: ${{ github.workspace }}
          fileName: 'myTemporaryFile.txt'
          encodedString: ${{ secrets.AZURE_ARM_SUBSCRIPTION_ID}}
      - name: cat
        run: cat $${{steps.write_file.outputs.filePath}}