name: Secret Test

on:
  pull_request:
  push:

jobs:
  show_secret:
    name: azure sub
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.AZURE_ARM_TENANT_ID}}

    steps:
      - name: Write File
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ${{ github.workspce }}/myTemporaryFile.txt
          contents: |
            echo ${{secrets.AZURE_ARM_SUBSCRIPTION_ID}}
          write-mode: overwrite
      - name: cat
        run: cat ${{ github.workspace }}/myTemporaryFile.txt